name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - JPVenson
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: source
    attributes:
      label: Source
      description: Where did you get Morestachio From.
      options:
        - Nuget
        - Github
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: What version/commit is this occuring.
      placeholder: 5.0.0.0/62fa3989b32f34ab5744ff44c5b5e25b15ecfb4a
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: Relevant Stacktrace output
      description: Please copy and paste any Stacktrace
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/JPVenson/morestachio/blob/master/CODE_OF_CONDUCT.md) and you are using the latest release of Morestachio
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I have vertified i am using the latest version of Morestachio
          required: true
