using System.ComponentModel.Design;
using Morestachio.Formatter.Framework;
using Morestachio.Formatter.Framework.Converter;
using Morestachio.Framework;

namespace Morestachio;

/// <summary>
///		Contains methods for handling partials
/// </summary>
public static class ParserOptionsDefaultPartialStoreExtensions
{
	/// <summary>
	///		Adds a new Named constant
	/// </summary>
	public static IParserOptionsBuilder WithDefaultPartialStore(this IParserOptionsBuilder builder, Func<DefaultPartialsStore, DefaultPartialsStore> config)
	{
		return builder.WithPartialsStore(() => config(new DefaultPartialsStore()));
	}

	/// <summary>
	///		Enables the use of the <see cref="PartialsStoreAggregator"/> to combine multiple <see cref="IPartialsStore"/>. Should be called before adding other partial stores in any way.
	/// </summary>
	public static IParserOptionsBuilder WithAggregatePartialStore(this IParserOptionsBuilder builder)
	{
		return builder.WithPartialsStore(new PartialsStoreAggregator());
	}

	/// <summary>
	///		Sets the <see cref="FileSystemPartialStore"/>
	/// </summary>
	/// <param name="directoryPath">Where on the file system should the Partials be enumerated</param>
	/// <param name="ignoreExtension">If set to true the files extension must not be included by <code>{{#IMPORT 'Filename'}}</code></param>
	/// <param name="ignoreFileStructure">If set to true all files can be accessed without setting the whole path</param>
	/// <param name="namePrefix">If set prefixes all partials generated by this store with the prefix</param>
	public static IParserOptionsBuilder WithFileSystemPartialStore(this IParserOptionsBuilder builder,
																	string directoryPath,
																	string searchPattern,
																	bool ignoreExtension,
																	bool ignoreFileStructure,
																	string namePrefix = null)
	{
		return builder.WithPartialsStore(() => new FileSystemPartialStore(directoryPath, searchPattern, ignoreExtension, ignoreFileStructure, namePrefix));
	}
}

/// <summary>
///		Contains methods for adding formatters in a structured way to an <see cref="IParserOptionsBuilder"/>
/// </summary>
public static class ParserOptionsBuilderFormatterExtensions
{
	/// <summary>
	///		Adds a new Named constant
	/// </summary>
	public static IParserOptionsBuilder WithConstant(this IParserOptionsBuilder builder, string name, object value)
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.Constants[name] = value;
			return c;
		});
	}

	/// <summary>
	///		Adds a new Named constant
	/// </summary>
	public static IParserOptionsBuilder WithConstant(this IParserOptionsBuilder builder, Func<(string, object)> value)
	{
		return builder.WithConfig(c =>
		{
			var (key, val) = value();
			c.Formatters.Constants[key] = val;
			return c;
		});
	}

	/// <summary>
	///		Adds a new Service
	/// </summary>
	public static IParserOptionsBuilder WithService<TService>(this IParserOptionsBuilder builder, TService value)
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.Services.AddService(value);
			return c;
		});
	}

	/// <summary>
	///		Adds a new Service
	/// </summary>
	public static IParserOptionsBuilder WithService<TService>(this IParserOptionsBuilder builder, Func<TService> value)
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.Services.AddService(value);
			return c;
		});
	}

	/// <summary>
	///		Adds a new Service
	/// </summary>
	public static IParserOptionsBuilder WithService<TServiceType, TServiceInstance>(this IParserOptionsBuilder builder,
																					TServiceInstance value)
		where TServiceInstance : class, TServiceType
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.Services.AddService<TServiceType>(value);
			return c;
		});
	}

	/// <summary>
	///		Adds a new Service
	/// </summary>
	public static IParserOptionsBuilder WithService<TServiceType, TServiceInstance>(this IParserOptionsBuilder builder,
																					Func<TServiceInstance> value)
		where TServiceInstance : class, TServiceType
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.Services.AddService<TServiceType>(value);
			return c;
		});
	}

	/// <summary>
	///		Adds a new <see cref="IServiceProvider"/> 
	/// </summary>
	public static IParserOptionsBuilder WithServiceProvider(this IParserOptionsBuilder builder,
															IServiceProvider subContainer)
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.Services.AddSubProvider(subContainer);
			return c;
		});
	}

	/// <summary>
	///		Adds formatters from an type
	/// </summary>
	public static IParserOptionsBuilder WithAllParametersAllDefaultValue(this IParserOptionsBuilder builder, bool value)
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.AllParametersAllDefaultValue = value;
			return c;
		});
	}

	/// <summary>
	///		Adds formatters from an type
	/// </summary>
	public static IParserOptionsBuilder WithValueConverter(this IParserOptionsBuilder builder, IFormatterValueConverter valueConverter)
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.ValueConverter.Add(valueConverter);
			return c;
		});
	}

	/// <summary>
	///		Adds formatters from an type
	/// </summary>
	public static IParserOptionsBuilder WithFormatters<T>(this IParserOptionsBuilder builder)
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.AddFromType<T>();
			return c;
		});
	}

	/// <summary>
	///		Adds formatters from an type
	/// </summary>
	public static IParserOptionsBuilder WithFormatters(this IParserOptionsBuilder builder, Type type)
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.AddFromType(type);
			return c;
		});
	}

	/// <summary>
	///		Adds an formatter
	/// </summary>
	public static IParserOptionsBuilder WithFormatter(this IParserOptionsBuilder builder, Delegate @delegate, string name)
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.AddSingle(@delegate, name);
			return c;
		});
	}

	/// <summary>
	///		Adds an formatter
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter(this IParserOptionsBuilder builder, Delegate @delegate, string name)
	{
		return builder.WithConfig(c =>
		{
			c.Formatters.AddSingleGlobal(@delegate, name);
			return c;
		});
	}

	#region Action Overloads

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithFormatter(this IParserOptionsBuilder builder, Action function, string name)
	{
		return builder.WithFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithFormatter<T>(this IParserOptionsBuilder builder, Action<T> function, string name)
	{
		return builder.WithFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithFormatter<T, T1>(this IParserOptionsBuilder builder, Action<T, T1> function, string name)
	{
		return builder.WithFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithFormatter<T, T1, T2>(this IParserOptionsBuilder builder, Action<T, T1, T2> function, string name)
	{
		return builder.WithFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithFormatter<T, T1, T2, T3>(this IParserOptionsBuilder builder, Action<T, T1, T2, T3> function, string name)
	{
		return builder.WithFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithFormatter<T, T1, T2, T3, T4>(this IParserOptionsBuilder builder, Action<T, T1, T2, T3, T4> function, string name)
	{
		return builder.WithFormatter((Delegate)function, name);
	}

	#endregion

	#region Function Overloads

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithFormatter<T>(this IParserOptionsBuilder builder, Func<T> function, string name)
	{
		return builder.WithFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithFormatter<T, T1>(this IParserOptionsBuilder builder, Func<T, T1> function, string name)
	{
		return builder.WithFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithFormatter<T, T1, T2>(this IParserOptionsBuilder builder, Func<T, T1, T2> function, string name)
	{
		return builder.WithFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithFormatter<T, T1, T2, T3>(this IParserOptionsBuilder builder, Func<T, T1, T2, T3> function, string name)
	{
		return builder.WithFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithFormatter<T, T1, T2, T3, T4>(this IParserOptionsBuilder builder, Func<T, T1, T2, T3, T4> function, string name)
	{
		return builder.WithFormatter((Delegate)function, name);
	}

	#endregion

	#region Action Overloads

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter(this IParserOptionsBuilder builder, Action function, string name)
	{
		return builder.WithGlobalFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter<T>(this IParserOptionsBuilder builder, Action<T> function, string name)
	{
		return builder.WithGlobalFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter<T, T1>(this IParserOptionsBuilder builder, Action<T, T1> function, string name)
	{
		return builder.WithGlobalFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter<T, T1, T2>(this IParserOptionsBuilder builder, Action<T, T1, T2> function, string name)
	{
		return builder.WithGlobalFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter<T, T1, T2, T3>(this IParserOptionsBuilder builder, Action<T, T1, T2, T3> function, string name)
	{
		return builder.WithGlobalFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter<T, T1, T2, T3, T4>(this IParserOptionsBuilder builder, Action<T, T1, T2, T3, T4> function, string name)
	{
		return builder.WithGlobalFormatter((Delegate)function, name);
	}

	#endregion

	#region Function Overloads

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter<T>(this IParserOptionsBuilder builder, Func<T> function, string name)
	{
		return builder.WithGlobalFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter<T, T1>(this IParserOptionsBuilder builder, Func<T, T1> function, string name)
	{
		return builder.WithGlobalFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter<T, T1, T2>(this IParserOptionsBuilder builder, Func<T, T1, T2> function, string name)
	{
		return builder.WithGlobalFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter<T, T1, T2, T3>(this IParserOptionsBuilder builder, Func<T, T1, T2, T3> function, string name)
	{
		return builder.WithGlobalFormatter((Delegate)function, name);
	}

	/// <summary>
	///		Adds a new Function to the list of formatters
	/// </summary>
	public static IParserOptionsBuilder WithGlobalFormatter<T, T1, T2, T3, T4>(this IParserOptionsBuilder builder, Func<T, T1, T2, T3, T4> function, string name)
	{
		return builder.WithGlobalFormatter((Delegate)function, name);
	}

	#endregion
}
