name: Test .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '2.2.x', '2.0', '3.0', '3.1.x', '5.0.x', '4.6', '4.6.1', '4.6.2', '4.7', '4.7.1', '4.7.2' ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
